#!/bin/bash
set -eo pipefail

host="$(hostname --ip-address || echo '127.0.0.1')"
port="${ELASTICSEARCH_PORT:-9200}"
pass="${ELASTICSEARCH_PASSWORD}"
user="${ELASTICSEARCH_USER}"

if [[ -n "${user}" && -n "${pass}" ]]; then
    curlAuth="${user}:${pass}@"
else
    curlAuth=""
fi

if healthCheck="$(curl -fsSL "http://${curlAuth}${host}:${port}/_cat/health?h=status")"; then

    # trim whitespace (otherwise we'll have "green ")
    healthCheck="$(echo "${healthCheck}" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')"

    # "yellow" should obviously only be an acceptable value on local for the
    # sake of getting the container to repsond as 'healthy.' In production
    # this should be tweaked.
    if [[ "${healthCheck}" = "green" || "${healthCheck}" == "yellow" ]]; then
        exit 0
    fi

    echo >&2 "Unexpected health status: ${healthCheck}"
fi

exit 1
